name: Update README

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Recent GitHub Activity - Profile Readme
        uses: Readme-Workflows/recent-activity@v2.4.0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
